(ns party.donut.single-page-app)

(defn data-fn
  "Example data-fn handler.

  Result is merged onto existing options data."
  [data]
  ;; returning nil means no changes to options data
  (comment
    '{:artifact/id  "test-app",
      :now/year     "2022",
      :top          "party.donut",
      :name         "party.donut/test-app",
      :now/date     "2022-11-08",
      :template     "party.donut/single-page-app",
      :group/id     "party.donut",
      :target-dir   "tmp/test-app",
      :template-dir "/Users/daniel/projects/work/donut/framework/single-page-app/resources/party/donut/single_page_app",
      :developer    "Daniel",
      :version      "0.1.0-SNAPSHOT",
      :main         "test-app",
      :scm/repo     "test-app",
      :user         "daniel",
      :scm/domain   "github.com",
      :raw-name     "party.donut/test-app",
      :scm/user     "party.donut"})
  nil)

(defn template-fn
  "Example template-fn handler.

  Result is used as the EDN for the template."
  [edn data]
  ;; must return the whole EDN hash map
  (comment
    '{:description "FIXME: generated by the party.donut/single-page-app template.",
      :data-fn     party.donut.single-page-app/data-fn,
      :template-fn party.donut.single-page-app/template-fn,
      :transform [["src" "src/{{top/file}}" {"main.clj" "{{main/file}}.clj"}]
                  ["test" "test/{{top/file}}" {"main_test.clj" "{{main/file}}_test.clj"}]]})
  edn)
